MonsantoCo/cloudformation-template-generator

README.md, build.sbt, project/build.properties, project/plugins.sbt, src/main/scala/com/monsanto/arch/cloudformation/model.scala, src/main/scala/com/monsanto/arch/cloudformation/model/Template.scala, src/main/scala/com/monsanto/arch/cloudformation/model/resource/IAM.scala, src/site/index.html, src/test/scala/com/monsanto/arch/cloudformation/model/CloudFormation_AT.scala, src/test/scala/com/monsanto/arch/cloudformation/model/IAMPolicy_UT.scala, src/test/scala/com/monsanto/arch/cloudformation/model/TemplateDoc_AT.scala, version.sbt
Bring master up to date. We seem to be moving away from master/develop/feature-branch and moving toward master/feature-branch. Perhaps we wil eliminate develop after the evil-deads branch is merged.
=> Merge develop into master

README.md, src/main/scala/com/monsanto/arch/cloudformation/model/resource/SNS.scala, version.sbt
Creates resources for SNS topics, subscriptions, and policies
=> Add SNS Support to CFTG

src/main/scala/com/monsanto/arch/cloudformation/model/resource/EC2.scala, src/test/resources/cloudformation-template-vpc-example.json, src/test/scala/com/monsanto/arch/cloudformation/model/CloudFormation_AT.scala
See a list of instance properties at http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html.
=> Adding DisableApiTermination to Instance properties.

src/main/scala/com/monsanto/arch/cloudformation/model/resource/S3.scala
Basically all the sub-types are now actually types rather than strings. Some are several layers deep. Types all the way down.
=> S3 support is more complete than before

src/main/scala/com/monsanto/arch/cloudformation/model/resource/ElasticLoadBalancing.scala, src/main/scala/com/monsanto/arch/cloudformation/model/simple/Builders.scala, src/main/scala/com/monsanto/arch/cloudformation/model/simple/SecurityGroupRoutable.scala, src/test/resources/cloudformation-template-vpc-example.json, src/test/scala/com/monsanto/arch/cloudformation/model/CloudFormation_AT.scala
Also standardize subtype nameing to be prefixed with ELB
This is a breaking change that should increment major version.
=> make ELB model more accurate and complete

src/main/scala/com/monsanto/arch/cloudformation/model/resource/HasArn.scala, src/main/scala/com/monsanto/arch/cloudformation/model/resource/SNS.scala, src/main/scala/com/monsanto/arch/cloudformation/model/resource/SQS.scala, version.sbt
fixes issue https://github.com/MonsantoCo/cloudformation-template-generator/issues/33
=> Add SQS primitives

src/main/scala/com/monsanto/arch/cloudformation/model/resource/EC2.scala
=> Adding support for EIPAssociation

src/main/scala/com/monsanto/arch/cloudformation/model/resource/EC2.scala, src/main/scala/com/monsanto/arch/cloudformation/model/simple/Builders.scala
=> Support peering connections in routes

src/main/scala/com/monsanto/arch/cloudformation/model/resource/EC2.scala, src/test/resources/cloudformation-template-vpc-example.json, src/test/scala/com/monsanto/arch/cloudformation/model/CloudFormation_AT.scala
=> Adding PrivateIpAddress attribute for Instance.

src/main/scala/com/monsanto/arch/cloudformation/model/resource/EC2.scala, src/test/resources/cloudformation-template-vpc-example.json, src/test/scala/com/monsanto/arch/cloudformation/model/CloudFormation_AT.scala
=> Add property MapPublicIpOnLaunch to subnet

README.md, src/main/scala/com/monsanto/arch/cloudformation/model.scala
=> Add documentation for aws interpolator

src/main/scala/com/monsanto/arch/cloudformation/model/AmazonFunctionCall.scala
=> add ConditionFunctionNestable

src/main/scala/com/monsanto/arch/cloudformation/model/simple/Builders.scala
Add in a NAT builder that allows you to supply your own EIP
=> Add in a NAT builder that allows you to supply your own EIP

README.md, src/main/scala/com/monsanto/arch/cloudformation/model/resource/ElasticSearch.scala, src/main/scala/com/monsanto/arch/cloudformation/model/resource/IAM.scala
=> Add support for elasticsearch

assets/custom-types/remote-route53/remote_route53.js
Added retry logic for PriorRequestNotComplete, with a retry cap of 100.
=> Fix race conditions on route 53 with retry logic

src/main/scala/com/monsanto/arch/cloudformation/model/resource/IAM.scala, src/test/scala/com/monsanto/arch/cloudformation/model/IAMPolicy_UT.scala
Followup to https://github.com/MonsantoCo/cloudformation-template-generator/pull/90
=> adding in a trait for IAMPolicyVersions

src/main/scala/com/monsanto/arch/cloudformation/model/resource/EC2.scala, src/test/scala/com/monsanto/arch/cloudformation/model/resource/EC2_UT.scala
Small change so that FromPort and ToPort can be parameterized
=> Ports in Security groups can now be parameterized

src/main/scala/com/monsanto/arch/cloudformation/model/resource/Kinesis.scala, src/test/scala/com/monsanto/arch/cloudformation/model/resource/Kinesis_UT.scala
I noticed that Kinesis support was not available, and needed it for my project
=> Add Kinesis support

src/main/scala/com/monsanto/arch/cloudformation/model/HasTemplate.scala, src/main/scala/com/monsanto/arch/cloudformation/model/TemplateBase.scala, src/test/scala/com/monsanto/arch/cloudformation/model/HasTemplateSpec.scala
Forgot to add this with https://github.com/MonsantoCo/cloudformation-template-generator/pull/120
=> add HasTemplate

src/main/scala/com/monsanto/arch/cloudformation/model/resource/CloudFormation.scala
=> stack parameters take Map[String, Token[String]].

src/main/scala/com/monsanto/arch/cloudformation/model/resource/Lambda.scala
This PR resolves https://github.com/MonsantoCo/cloudformation-template-generator/issues/95 by adding support for Version and Alias resources.
=> Issue 95 lambda alias version

src/main/scala/com/monsanto/arch/cloudformation/model/Parameter.scala
Needed to add this for (at least) ElasticSearch parameters that expected a Token[Boolean]
=> Added BooleanParameter

src/main/scala/com/monsanto/arch/cloudformation/model/resource/ECS.scala
=> Add DependsOn parameter to AWS::ECS::Service and AWS::ECS::Cluster

src/main/scala/com/monsanto/arch/cloudformation/model/resource/RDS.scala
Fixes #150
Also changed `RDSDBSecurityGroupRule.EC2SecurityGroupOwnerId` from `Option[String]` to `Option[Token[String]]`.
=> Change `AWS::RDS::DBInstance`'s `Option[A]`s to `Option[Token[A]]`

src/main/scala/com/monsanto/arch/cloudformation/model/resource/Route53.scala
=> Allow creation of alias records by hosted zone ID

README.md, src/main/scala/com/monsanto/arch/cloudformation/model/resource/ElasticLoadBalancingV2.scala, src/test/scala/com/monsanto/arch/cloudformation/model/FnIf_UT.scala, src/test/scala/com/monsanto/arch/cloudformation/model/TemplateDoc_AT.scala, src/test/scala/com/monsanto/arch/cloudformation/model/resource/ElasticLoadBalancingV2_UT.scala
Fixes #106
This is based on the initial work by @carsonfarrell in PR #128.
Closes #128
=> Implement support for ElasticLoadBalancingV2

src/main/scala/com/monsanto/arch/cloudformation/model/resource/Logs.scala
=> Add suport for AWS::Logs::*

src/main/scala/com/monsanto/arch/cloudformation/model/resource/ElasticLoadBalancingV2.scala, src/test/scala/com/monsanto/arch/cloudformation/model/resource/ElasticLoadBalancingV2_UT.scala
Fixes MonsantoCo/cloudformation-template-generator#171
=> Add `host-header` RuleCondition builder method

src/main/scala/com/monsanto/arch/cloudformation/model/resource/ElasticLoadBalancingV2.scala
=> Make RuleCondition accept Option[Seq[Token[String]]]

src/main/scala/com/monsanto/arch/cloudformation/model/resource/ElasticLoadBalancingV2.scala
* `AWS::ElasticLoadBalancingV2::Listener`
* `AWS::ElasticLoadBalancingV2::ListenerRule`
Fixes #181
=> Add DependsOn attribute to ElasticLoadBalancingV2 resources

src/main/scala/com/monsanto/arch/cloudformation/model/resource/AutoScaling.scala, src/test/scala/com/monsanto/arch/cloudformation/model/CloudFormation_AT.scala
Closes MonsantoCo/cloudformation-template-generator#194
=> Make AWS::AutoScaling::AutoScalingGroup DesiredCapacity optional

src/main/scala/com/monsanto/arch/cloudformation/model/resource/CloudWatch.scala
Closes MonsantoCo/cloudformation-template-generator#185
=> Add support for TreatMissingData parameter of AWS::CloudWatch::Alarm

src/main/scala/com/monsanto/arch/cloudformation/model/resource/CodeCommit.scala, src/test/scala/com/monsanto/arch/cloudformation/model/resource/CodeCommit_UT.scala
Patching a few changes on top of PR #193
=> Add AWS::CodeCommit::Repository

src/main/scala/com/monsanto/arch/cloudformation/model/resource/Batch.scala, src/test/scala/com/monsanto/arch/cloudformation/model/resource/BatchTest.scala
Fixes #199
Tested create/update/delete cycle with CloudFormation.
=> Add support for AWS::Batch::*

src/main/scala/com/monsanto/arch/cloudformation/model/resource/ECS.scala
=> Add Placement Constraints and Strategies to AWS::ECS::Service

src/main/scala/com/monsanto/arch/cloudformation/model/resource/S3.scala
=> Adding in QueueNotification for S3 buckets as well as notification Filters

src/main/scala/com/monsanto/arch/cloudformation/model/resource/Logs.scala
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-destination.html#cfn-logs-destination-destinationpolicy
=> Make `AWS::Logs::Destination`.DestinationPolicy take a Token[String]

src/main/scala/com/monsanto/arch/cloudformation/model/resource/Lambda.scala, src/test/scala/com/monsanto/arch/cloudformation/model/resource/Lambda_UT.scala
=> Make TracingConfig an enum

src/main/scala/com/monsanto/arch/cloudformation/model/Parameter.scala, src/main/scala/com/monsanto/arch/cloudformation/model/resource/EC2.scala, src/main/scala/com/monsanto/arch/cloudformation/model/resource/ElasticLoadBalancingV2.scala, src/main/scala/com/monsanto/arch/cloudformation/model/resource/RDS.scala, src/main/scala/com/monsanto/arch/cloudformation/model/simple/Builders.scala, src/test/scala/com/monsanto/arch/cloudformation/model/FnIf_UT.scala, src/test/scala/com/monsanto/arch/cloudformation/model/ResourceRef_UT.scala, src/test/scala/com/monsanto/arch/cloudformation/model/resource/EC2_UT.scala, src/test/scala/com/monsanto/arch/cloudformation/model/resource/ElasticLoadBalancingV2_UT.scala
This PR partially addresses issue #102 / #107  with regard to VPC ID references.
=> add VpcRef ADT to allow VPC ID to be set more flexibly

src/main/scala/com/monsanto/arch/cloudformation/model/resource/AutoScaling.scala
- Add AssociatePublicIpAddress field to LaunchConfiguration
- Tested and OK
=> Add AssociatePublicIpAddress field to LaunchConfiguration.

src/main/scala/com/monsanto/arch/cloudformation/model/resource/EC2.scala
- Make GroupDescription a Token type.
- Tested and works.
=> Add GroupName support for security group.

src/main/scala/com/monsanto/arch/cloudformation/model/resource/EKS.scala, src/test/scala/com/monsanto/arch/cloudformation/model/resource/EKS_UT.scala
- Add EKS support and unit test.
=> Add EKS support and unit test.

src/main/scala/com/monsanto/arch/cloudformation/model/resource/DynamoDB.scala, src/test/scala/com/monsanto/arch/cloudformation/model/resource/DynamoDBSpec.scala
See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-pointintimerecoveryspecification
=> Adds support for PointInTimeRecoverySpecification and Tags

src/main/scala/com/monsanto/arch/cloudformation/model/resource/ApplicationAutoScaling.scala
See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-applicationautoscaling-scalingpolicy.html
=> Adds support for TargetTrackingScalingPolicyConfiguration

src/main/scala/com/monsanto/arch/cloudformation/model/resource/IAM.scala
Hello,
Request to add the PermissionsBoundary property to the AWS Role via this pull request.
tia,
Alex
=> Added PermissionsBoundary for Role

src/main/scala/com/monsanto/arch/cloudformation/model/resource/SSM.scala
This change modifies SSM documents to work as either command documents or automation documents (the current ones only work as command documents.  The change only adds optional parameters (which default to `None`) and will not break any existing code.
=> Added automation features to SSM Documents

src/main/scala/com/monsanto/arch/cloudformation/model/resource/Lambda.scala
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
Nodejs runtime update to 14.x
What is the current behavior?
The current run time is 10.x
Will this require a change in documentation (if this is a feature change)?
no
Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)
no
Other information:
=> Changes to add Nodejs14.x runtime
