MonsantoCo/cloudformation-template-generator

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Redshift.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Route53.scala
Added:
AWS::Redshift::Cluster
AWS::Redshift::ClusterSecurityGroup
AWS::Redshift::ClusterSecurityGroupIngress
AWS::Redshift::ClusterParameterGroup (along with helper RedshiftClusterParameter type)
AWS::Redshift::ClusterSubnetGroup
Note: I have not tried creating a cluster so I do not know if there could be mistakes there but I have
used ClusterSecurityGroup, and ClusterSecurityGroupIngress both of which appear to work fine.
Addresses issue #8
> Add model support for Redshift

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Route53.scala
Use Token[String] instead of String so we can put Ref values there.
Originally submitted against master, resubmitting against develop.
> Change type on AWS::Route53::HostedZone Name

- src/main/scala/com/monsanto/arch/cloudformation/model/AmazonFunctionCall.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/AutoScaling.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Resource.scala
Adds the an optional [UpdatePolicy](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html) for AWS::AutoScaling::AutoScalingGroup
It does not go under `Properties`, it is a separate section like `Metadata`, so I made some slight changes to the `Resource` code rather than add another bit of code that extends it.  Nothing else uses `UpdatePolicy` as far as I know, but it seemed like the logical place to put it.  I already used it in production, it seems to work so far.  When I changed the launch config, it replaced all my nodes with new ones automatically like it is supposed to.
Great work on this code, it is easy to use and extend!  By far the best solution I've seen for managing the templates.
> Add UpdatePolicy support to AutoScalingGroup

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/S3.scala
S3LoggingConfiguration.DestinationBucketName should be a ResourceRef to a bucket, not an actual bucket
> Bug fix for S3LoggingConfiguration DestinationBucketName

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/AutoScaling.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/EC2.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/ElasticLoadBalancing.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Resource.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/simple/Builders.scala
- src/test/resources/cloudformation-template-vpc-example.json
- src/test/scala/com/monsanto/arch/cloudformation/model/CloudFormation_AT.scala
DependsOn is an `Option[Seq[String]]`, which has two drawbacks: Option is superfluous for Seq and it should actually be a Seq of ResourceRefs. Unfortunately, CloudFormation requires a list of strings. Also, I did not change the implementation of DependsOn, I just added it to a bunch of resource types and their builders.
We can revisit the backward-compatibility breaking changing to something like `Seq[ResourceRef[_]]` at a later date. There are significant type/JSON-serialization challenges to making that work. Plus, including DependsOn even when empty will bloat the template a bit.
> added DependsOn to more resources and their builders

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/AutoScaling.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/simple/Builders.scala
I'm using this in the Vault VPC to specify an additional volume for the vault data so I can snapshot it without an outage.  Looks to work fine.
> Modeled Autoscaling EBS parameters

- src/main/scala/com/monsanto/arch/cloudformation/model/Template.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/Template_UT.scala
If we set two resources with the same name, now we fail to create the template, instead of creating a template that will not work the way we want.
> Remove dupes

- build.sbt
- src/main/scala/com/monsanto/arch/cloudformation/model/EnumFormat.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/CloudWatch.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/ElasticLoadBalancing.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/RDS.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Resource.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/simple/Builders.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/RDS_UT.scala
Implement a complex mechanism for reducing the chance of creating JSON
for an RDS DBInstance that is invalid.  My hope is that the complexity
equals and is not greater than the complexity inherent in the
restrictions around RDS creation.  There is still one run-time check
around storage encryption since specifying it is only valid on new
instances created within VPCs.
A couple other minor changes:
-   Clean up build.sbt
-   Implement and use EnumFormat for all enumerations JSON serialization
When this change gets merged, the release will have to increment the major version number since this breaks RDS backward compatibility badly.
> Reduce ability to create invalid RDS template

- src/main/scala/com/monsanto/arch/cloudformation/model.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/AwsStringInterpolation.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/AwsTokenSpec.scala
added a string interpolator that generates Fn:Join statements by using scala string interpolation.
For example:
```
val token : Token[String] = ParameterRef(bucketNameParameter)
val string = aws"s3://$token/my/s3/path"
```
BTW, the guidelines for contributing has a broken link
> Aws token string interpolation

- src/main/scala/com/monsanto/arch/cloudformation/model.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/IAM.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/IAMPolicy_UT.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/JsonWritingMatcher.scala
Added support for IAM policy conditions
> Iam policies - Add Conditions

- src/main/scala/com/monsanto/arch/cloudformation/model/Condition.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/Mapping.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/Output.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/Parameter.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/Template.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Resource.scala
Fixes #45.
Using ListMap to hold elements, which are traversed in the same order they are added.
> preserving object order

- src/main/scala/com/monsanto/arch/cloudformation/model/AmazonFunctionCall.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/FnGetAZs_UT.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/FnIf_UT.scala
Also corrected the conditional functions that took conditions as
arguments to now take ConditionRef.  The ConditionRef change breaks
backward compatibility, so releasing should probably increment the major
version number.
> Add support for Fn::GetAZs

- src/main/scala/com/monsanto/arch/cloudformation/model/AmazonFunctionCall.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/ConditionFunctionNestable_UT.scala
Rolls back a portion of https://github.com/MonsantoCo/cloudformation-template-generator/pull/57 to fix https://github.com/MonsantoCo/cloudformation-template-generator/issues/60.  This only fixes it in the sense that it works again and adds unit tests for the cases that #57 broke.  I'll leave #60 open as we'd like to add better type safety as was intended.  However, I'm running into issues with getting it to work with all the implicits involved in the `AmazonFunctionCall` and `Token` conversions, and I need to move on for now.
> Fix `Fn::Not`, `Fn::And`, and `Fn::Or`

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/EC2.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/simple/Builders.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/CloudFormation_AT.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/ResourceRef_UT.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/RDS_UT.scala
[AWS CF Subnet Doc](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-subnet.html#cfn-ec2-subnet-availabilityzone)
> AvailabilityZone is optional for Subnet

- CHANGELOG.md
- src/main/scala/com/monsanto/arch/cloudformation/model/AmazonFunctionCall.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/ConditionFunctionNestable_UT.scala
I ran into a case where I needed to do something like: Fn::And(Fn::Not(Fn::Equal), Fn:Equal). This wasn't currently supported. I'm guessing we just missed it with https://github.com/MonsantoCo/cloudformation-template-generator/issues/60 and https://github.com/MonsantoCo/cloudformation-template-generator/pull/66 . I don't think this should have any affect on legacy code.
> Add support for nesting a Fn::Not

- src/main/scala/com/monsanto/arch/cloudformation/model/Parameter.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/RDS.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/RDS_UT.scala
DBSubnetGroupName and EC2VpcId can now be passed as ParameterRef
> Parameterized VPC and security group for RDS

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/CloudWatch.scala
Amazon added Lambda CloudWatch alarms. This PR adds the namespace to the `AWS::CloudWatch::Alarm::Namespace` enum. See [http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/lam-metricscollected.html#lambda-cloudwatch-metrics]() for reference on the namespace.
> Add AWS/Lambda CloudWatch Alarm Namespace

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/IAM.scala
Version defaults to 2008-10-17, but some cloudformation directives
require '2012-10-17', such as AWS::IAM::ManagedPolicy
http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html#Version
> Add Version attribute to IAM Document

- README.md
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/ApiGateway.scala
The documentation for API Gateway on Cloudformation is not that good - it says that almost everything is Optional, but then when you actually run it, it has to be set. This works for my current use cases, but there are somethings that are probably not Option[_].
> add API Gateway

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Lambda.scala
Fix for #97 makes the Description property an `Option[Token[String]]`
> [#97] Make AWS::Lambda::Function#Description Option[Token[String]]

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/CloudFormation.scala
Fixes #99 by adding support for AWS::CloudFormation::Stack
> [#99] Implement support for AWS::CloudFormation::Stack 

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/IAM.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/IAMRole_UT.scala
Closes #104. I added in an implicit that should allow for seamless backwards compatibility.
> adding support for built-in AWS policies

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/DynamoDB.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/DynamoDBSpec.scala
CloudFormation will make a maximum of ten tables at one time. Making more than that requires chaining them together with "DependsOn" attributes.
> Add "DependsOn" to AWS::DynamoDb::Table

- README.md
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/EC2.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/ECR.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/ElastiCache.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/ElasticBeanStalk.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/RDS.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/EC2_UT.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/ECR_UT.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/ElastiCache_UT.scala
- Added the following resources:
- AWS::EC2::SubnetNetworkAclAssociation
- AWS::ElastiCache::CacheCluser
- AWS::ElastiCache::SubnetGroup
- AWS::ECR::Repository
- Added an io1 disk type.
- Added the MariaDB database engine.
We are creating our EB template configurations and environments in the same Cloudformation template. The default `TemplateName` parameter type of Option[String] was making this very difficult, so I changed it to `TemplateName: Option[ResourceRef[`AWS::ElasticBeanstalk::ConfigurationTemplate`]]`. Please advise if there is a better/smarter way of going about this; the way I did this will break existing templates.
Our database port is configured as a parameter. This means that the standard `Option[String]` doesn't work for us. I changed the database port parameter type to …
> Added resources and changed a parameter or two.

- CHANGELOG.md
- README.md
- src/main/scala/com/monsanto/arch/cloudformation/model/AmazonFunctionCall.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/Output.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/simple/Builders.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/IntrinsicFunctions_UT.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/Template_UT.scala
See https://aws.amazon.com/blogs/aws/aws-cloudformation-update-yaml-cross-stack-references-simplified-substitution/
> Added support for cross-template references and Fn::Sub

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/IAM.scala
This seems to resolve #138, at least in my testing locally.
I added the `Id` field to the `PolicyDocument` as well, although I don't specifically need it for my use case. (I thought its absence seemed likely to have been an oversight.)
> Add support for Id and Sid to IAM policies and statements

- src/main/scala/com/monsanto/arch/cloudformation/model/AmazonFunctionCall.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/ApiGateway.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/AutoScaling.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/CloudFormation.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/CloudWatch.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/EMR.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/ElastiCache.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/ElasticLoadBalancing.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/IAM.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Lambda.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Route53.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/SQS.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/simple/Builders.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/FnSplit_UT.scala
Resolves #140.
Because `Fn::Split` logically returns `Seq[Token[String]]`, I wanted to make sure it could be used anywhere `Seq[Token[String]]` is used today. That's why I added the `TokenSeq[R]` (which is a type alias for an `Either`): either the caller can use a hard-coded sequence of strings (or `Token[String]`s), or they can use `Fn::Split`. In the first case, the resulting JSON is a `JsArray`, and in the second, the resulting JSON is a `JsObject`. Either way, the `Either` should be fairly transparent to the caller because there are implicit functions that lift values into the `Left` or `Right` as appropriate.
> add support for Fn::Split

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/ECS.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/ECS_UT.scala
Partially addresses #132. 
I hope to eventually add at least `AWS::ECS::Service` as well, but we could use this `AWS::ECS::TaskDefinition` now, in templates that define task definitions for batch jobs that aren’t run as services.
> add support for ECS Task Definitions, Services, and Clusters

- src/main/scala/com/monsanto/arch/cloudformation/model/AmazonFunctionCall.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/IAM.scala
- src/test/resources/cloudformation-template-vpc-example.json
- src/test/scala/com/monsanto/arch/cloudformation/model/IAMPolicy_UT.scala
This should make writing policy statements that affect multiple resources a lot cleaner. Right now, AFAICT you have to break them out into multiple statements, which is hard to read in the generated template and, eventually, the generated policy. [Multiple resources are supported by IAM.](http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html#Resource)
This should be backwards-compatible with the exception that one has to 
```scala
import com.monsanto.arch.cloudformation.model.resource.PolicyStatement._
```
to get the implicits. I'm open to moving them to another location that is more likely to already be imported if someone has an idea of where that might be.
The generated JSON will now always contain an array for the `Resource` field, but that should have no …
> Update IAM Policy Statements to support multiple resources

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/IAM.scala
Fixes #148 
This may warrant a minor version bump. The implicit conversion from `String` to `Token[String]` should take care of `InstanceProfile`. Since there's also an implicit conversion from `T` to `Option[T]`, if people did not explicitly specify the `Path` in `ManagedPolicy` as `Some("blah")`, compilation will fail since only one implicit conversion will be applied.
> Change `Path` type in IAM resources to be `Token[String]`

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/ApiGateway.scala
This adds the missing ProviderArns to `AWS::ApiGateway::Authorizer` as
described here http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-authorizer.html#cfn-apigateway-authorizer-providerarns
> Add ProviderArns to `AWS::ApiGateway::Authorizer`

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/ECS.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/ECS_UT.scala
The TaskDefinition also validates that the any ContainerDefinitions' MountPoints' SourceVolume names matche one of the Volumes in the TaskDefinition.
Fixes #163
> Add support for ContainerDefinition MountPoints

- .travis.yml
This is just something I noticed while waiting for a PR check to complete. We've noticed that caching these two directories definitely helps speed up build time.
> Cache the ivy cache, compiled compiler interface, etc.

- src/main/scala/com/monsanto/arch/cloudformation/model.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/RDS.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/RDS_UT.scala
It turned out that this wasn't as difficult as I imagined it would be. It does verify that allocated storage is specified for a NewRds instances where it would make no sense for that property to be omitted.
Fixes MonsantoCo/cloudformation-template-generator#172
> Make AllocatedStorage optional for non-NewRds instances

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/IAM.scala
* Added name field for managed policies and IAM groups.
* Changed AWS::IAM::Group managed policy parameter type to match  AWS::IAM::Role. The previous type was  ```Option[Seq[ResourceRef[`AWS::IAM::ManagedPolicy`]]]```, this causes issues when not creating a resource and using predefined AWS managed policies.
> Align managed policy arns parameter types

- README.md
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/ApiGateway.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/ApiGateway_UT.scala
I had a few questions while writing this that I'd like to understand better:
- Why do some resources override `DependsOn` but others do not?
- Why do some unit test files are Foo_UT.scala and others are FooSpec.scala?
- For `KeyType` there is currently only one legal value, `"API_KEY"`.  Should that be a default parameter?  I don't see many (besides `None`) of those in your code base.
> Add AWS::ApiGateway::{UsagePlan,UsagePlanKey}

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/SSM.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/SSM_UT.scala
This adds support for all of the current CloudFormation SSM resources. I have tested (in real life) parameters, associations, and command documents.
Full disclosure: I have not tested, because I have no current need for, automation or policy documents. There may be subtle (or not so subtle) bugs in those.
Closes #191
> Add support for EC2 Systems Manager

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/CodeBuild.scala
There is no reason for this to be a static String.
> Change CodeBuildProjectArtifacts.Path to Token[String]

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/CloudWatch.scala
from: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/aws-namespaces.html
> adding in all the AWS::CloudWatch::Alarm::Namespaces

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Logs.scala
Fixes #231
This change will allow metric filters to use pre-existing log groups. It should be backwards compatible since `ResourceRef` extends `Token[String]`.
> Make LogGroupName in MetricFilter and SubscriptionFilter accept Token[String]

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Lambda.scala
Fixes #229
Also adds missing parameters for AWS::Lambda::Permission and AWS::Lambda::Alias as well as documentation.
> Add missing AWS::Lambda::Function parameters

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Logs.scala
This will break clients that use DependsOn or Condition.
I could add more constructors if there are callers, but
given that the constructor was private until now
I'm hoping it won't be necessary.
> Make LogGroup.RetentionInDays optional

- src/main/scala/com/monsanto/arch/cloudformation/model/Output.scala
This is a breaking change.  Adding an apply function like so
@deprecated("Please use default constuctor", "3.7.2")
def apply[R](name: String, Description: String, Value: Token[R], Export: Option[Token[String]] = None)(implicit format: JsonFormat[Token[R]]): Output[R] =
apply(name, Some(Description), Value, Export)
is not possible because there are multiple values with default parameters.
> Make Output.Description optional

- src/main/scala/com/monsanto/arch/cloudformation/model/Template.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/TemplateBase.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Events.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/CloudFormation_AT.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/TemplateBaseSpec.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/TemplateDoc_AT.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/Template_UT.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/ApiGateway_UT.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/CodeCommit_UT.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/Route53_UT.scala
This is a breaking change.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-anatomy.html
I think it's worth the pain.  It's bad to have one of the most primitive
data structures not match the spec.
> Make Template match documentation

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/IAM.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Lambda.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/IAMPolicy_UT.scala
The existing Policy is incorrect for two reasons
- There is an incorrect constraint on Policies saying there can only be one of Users/Groups/Roles
- The type of Users/Groups/Roles is too restrictive, not allowing a caller to
refer to an existing resource
I think the author may have meant to ensure there is at least one of
Users/Groups/Roles.  I added that as a require.
(This CR also fixes a trivial compilation warning.)
> Fix IAM Policies

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/ElasticSearch.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/BatchTest.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/EFS_UT.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/ElasticSearchDomain_UT.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/SSM_UT.scala
- Add support for VPCOptions. This allows you to make your elastic search domain privately accessible.
- Add the ability to attach tags to elastic search domain.
- Added unit test.
- Tests did not work for me (possibly windows with \r\n?). Now comparing actual json's instead of pretty printed jsons.
Should be backwards compatible.
> Upgrade/extend `AWS::Elasticsearch::Domain` to support VPCOptions

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Events.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/Events_UT.scala
Fixes a serialization bug.  `JsValue` does not work.
> Change Events::Rule target Input to Token[String]

- src/main/scala/com/monsanto/arch/cloudformation/model/Template.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/Template_UT.scala
Now that these are options, we should handle template addition by looking at the two and preserving left if right is None.
> Handle template addition for Description and AWSTemplateFormatVersion

- src/main/scala/com/monsanto/arch/cloudformation/model/AmazonFunctionCall.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/AmazonTag.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/AutoScaling.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/EC2.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/simple/Builders.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/CloudFormation_UT.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/RDS_UT.scala
Changed to just use Token[String].  The AMIId wrapper added little value and made it more difficult to look AMIs up from a custom Lambda.
This change also adds some implicit conversion helpers.
> Amiid deprecation

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/AmazonTag.scala
- src/main/scala/com/monsanto/arch/cloudformation/model/simple/Builders.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/RDS_UT.scala
Since the "name" in the template is typically a constant, and the stack name is what varies, put stack name first.  Also tweaked a few other things, such as removing "VPC" from the VPC name tag by default.  Pass in a name if you have more than one VPC per stack.
> Switched fromName tag generator to put the stack name first.

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Lambda.scala
- Adds Node 8.10 as a runtime option
- Adds 'Tags' as a field for `AWS::Lambda::Function` as per [the cloudformation spec](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html).
> Some minor updates to the Lambda module

- CHANGELOG.md
- README.md
- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Kinesis.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/Kinesis_UT.scala
The Kinesis Firehose CF types are more than complicated enough that I don't want to do proper additions of all possible types. I added placeholders for Non-S3 versions, to be added as needed.
(Note: I'd not release a version of CFTG just yet. Clean the deck of PRs first.)
> Kinesis Firehose S3 support

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/DynamoDB.scala
- src/test/scala/com/monsanto/arch/cloudformation/model/resource/DynamoDBSpec.scala
Extended on [this PR](https://github.com/MonsantoCo/cloudformation-template-generator/pull/266)
to get the BillingMode PAY_PER_REQUEST even better supported.
Implemented the check (and tests) that ProvisionedThroughput is also not allowed in the GlobalSecondaryIndexes 
when PAY_PER_REQUEST is enabled.
> BillingMode PAY_PER_REQUEST validation also for GlobalSecondaryIndexes

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/Lambda.scala
Also added deprecation warnings to versions of node that have been marked as deprecated by AWS.
> Added new lambda runtimes for Node 10 and Python 3.7

- src/main/scala/com/monsanto/arch/cloudformation/model/resource/IAM.scala
Added tagging for IAM roles.  The field is optional and `None` by default, so it should not break any existing code.
> Added tags to IAM roles
